-- ADT (5a)
-- BESTA := TUPLE OF(ARTNR:NUMBER, MENGE:NUMBER, WERT:FLOAT)

CREATE OR REPLACE TYPE BESTA AS OBJECT(
    ARTNR number,
    MENGE number,
    WERT float
);

CREATE OR REPLACE TYPE BESTA_NT AS TABLE OF BESTA;

CREATE TABLE BESTELLAT (
    BSTNR NUMBER PRIMARY KEY,
    KNR NUMBER,
    STATUS NUMBER,
    RSUM NUMBER(12,2),
    BESTDAT DATE,
    LIEFDAT DATE,
    RECHDAT DATE,
    ARTLIST BESTA_NT
)
NESTED TABLE ARTLIST STORE AS ARTLIST_TAB;

ALTER TABLE BESTELLAT ADD FOREIGN KEY (KNR) REFERENCES KUNDE(KNR);
-- ALTER TABLE ARTLIST_TAB ADD FOREIGN KEY (ARTNR) REFERENCES ARTIKEL(ARTNR);
